Исправление перевода
Paprikar/aria-2-subs pull request #1
Opened 2023-06-07 15:17 UTC by Paprikar

Исправил перевод:
- Русалка -> Ундина
- Человеческий Дом -> Земля
- Волшебница Воды -> Водная Фея
- Косички -> Хвостики
- Смущающие замечания -> Смущающие высказывания

2023-06-07 15:42 UTC, KusanagiMajor commented on [15] Aria TV 2 01 серия.ass
>  Dialogue: 0,0:09:39.73,0:09:40.68,Default,,0,0,0,,Коняшка?
Коняшка?)))

2023-06-07 15:44 UTC, KusanagiMajor commented on [15] Aria TV 2 01 серия.ass
>  Dialogue: 0,0:09:39.73,0:09:40.68,Default,,0,0,0,,Коняшка?
Надо проверить кто это говорит

2023-06-07 15:45 UTC, Paprikar commented on [15] Aria TV 2 01 серия.ass
>  Dialogue: 0,0:09:39.73,0:09:40.68,Default,,0,0,0,,Коняшка?
Проверил, в контексте всё правильно

2023-06-07 16:18 UTC, KusanagiMajor commented on [14] Aria TV 2 Sp 1 серия.ass
Смущающие **замечания** запрещены!

2023-06-08 10:21 UTC, hotoshi commented on [15] Aria TV 2 01 серия.ass
199 Все люди, который (которых) я встретила на Акве, собрались вместе.

2023-06-08 10:46 UTC, KusanagiMajor commented on [40] Aria TV 2 26 серия.ass
Строка 325
"В детстве я хотела стать волшебницей."
И следующий за ней диалог выглядит так будто это игра слов и речь именно про фею.

Это не давало мне покоя, потому я на слух примерно разобрал что они говорят:
> 子供の頃は**妖精**になりたいともってました
> **妖精**?
> はい、色んなところお飛び回って、みんあお幸せするような
> へへ、成れるんじゃない？
> おおえ？
> あかりちゃんももうすん**妖精**さんに
> おお

Если пропустить это через deepl то получится:
> When I was a child, I wanted to be a **fairy**.
> **Fairy**?
> Yes, I wanted to fly around and make people happy.
> Heh, you can do that, can't you?
> Oh, yeah?
> Akari, you'll be a **fairy** soon, too.
> Oh!

2023-06-08 10:56 UTC, hotoshi commented on [18] Aria TV 2 04 серия.ass
191 Я буду грести назад.
192 Грести назад?

Может "Задом наперёд"?

2023-06-08 11:16 UTC, KusanagiMajor commented on [40] Aria TV 2 26 серия.ass
И google и deepl переводят 妖精 (ようせい) как fairy, но куда важнее то, что это то же слово что они употребляют, когда говорят про водных фей - 水の妖精, где 水 это вода, а の это частица показывающая принадлежность одного к другому (откуда и получается "фея воды", или же "водная фея").

В общем важно использовать то же слово, потому как конец диалога это именно намёк на то что она станет Водной Феей.

2023-06-08 11:19 UTC, Paprikar commented on [18] Aria TV 2 04 серия.ass
@KusanagiMajor ты уже проверил с видеорядом?

2023-06-08 11:29 UTC, KusanagiMajor commented on [18] Aria TV 2 04 серия.ass
@Paprikar проверил, но там и по диалогу было понятно что они торопятся.

2023-06-08 13:33 UTC, KusanagiMajor approved these changes

2023-06-08 13:35 UTC, KusanagiMajor approved these changes

2023-06-08 16:41 UTC, KusanagiMajor requested changes

2023-06-08 16:41 UTC, KusanagiMajor commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:10:18.89,0:10:24.81,Default,,0,0,0,,Фактически, это кафе открылось более чем 580 лет назад в Венеции на Земле,
в Земной Венеции

2023-06-08 16:41 UTC, KusanagiMajor commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:14:17.64,0:14:24.88,Default,,0,0,0,,Это то, что сказал Наполеон о площади Сан Марко давным-давно на Земле.
Святого Марко (возможно в других местах тоже нужно заменить)

2023-06-08 16:41 UTC, KusanagiMajor commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:01:01.08,0:01:06.67,Default,,0,0,0,,На Земле погода всегда стабильна, но мне больше нравится Аква.
いつもお天気だったけど

"всегда была хорошая погода"
или
"погода всегда была хорошая"

2023-06-08 16:41 UTC, KusanagiMajor commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:12:17.01,0:12:19.02,Default,,0,0,0,,Вы двое, Смущающие высказывания запрещены!
Настолько смущающие что с большой буквы?)

2023-06-08 16:41 UTC, KusanagiMajor commented on [17] Aria TV 2 03 серия.ass
>  Dialogue: 0,0:22:17.44,0:22:23.73,Default,,0,0,0,,{\i1}Благодаря Ал-чану, сегодняшняя ночь метеоритного дождя прошла в тишине.
"Ал-чану" это если что не ошибка, так не только к девочкам но и к детям обращаются (хоть он их и старше)

2023-06-08 16:41 UTC, KusanagiMajor commented on [23] Aria TV 2 09 серия.ass
> +Dialogue: 0,0:03:44.27,0:03:47.98,Default,,0,0,0,,и быстро стал очень популярным\Nв Венеции на Земле.
Земной Венеции

2023-06-08 16:41 UTC, KusanagiMajor commented on [32] Aria TV 2 18 серия.ass
> +Dialogue: 0,0:20:56.49,0:20:58.32,Default,,0,0,0,,Да, но Смущающие высказывания запрещены!
Опять слишком смущающие высказывания, что аж с большой буквы

2023-06-08 16:41 UTC, KusanagiMajor commented on [34] Aria TV 2 20 серия.ass
> +Dialogue: 0,0:06:04.05,0:06:11.39,Default,,0,0,0,,Эти колонны всегда были олицетворением города, даже в Венеции на Земле.
Земной Венеции

2023-06-08 16:41 UTC, KusanagiMajor commented on [38] Aria TV 2 24 серия.ass
>  Dialogue: 0,0:07:21.86,0:07:24.19,Default,,0,0,0,,Атена-семпай - Сирена.
Афина-семпай (надо проверить в других местах)

![](https://img33.imgslib.link//manga/aria/chapters/5-22/11.png)

2023-06-08 16:52 UTC, KusanagiMajor commented on [38] Aria TV 2 24 серия.ass
>  Dialogue: 0,0:07:21.86,0:07:24.19,Default,,0,0,0,,Атена-семпай - Сирена.
Скрин из переведённой манги это так себе пруф конечно, но я считаю перевод манги очень удачным в плане адаптации, потому что он действительно притно воспринимается без всякого кринжа, так что беру его за эталон.

2023-06-08 17:27 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
>  Dialogue: 0,0:22:17.44,0:22:23.73,Default,,0,0,0,,{\i1}Благодаря Ал-чану, сегодняшняя ночь метеоритного дождя прошла в тишине.
Так мне это исправлять или как?)))

2023-06-08 17:51 UTC, KusanagiMajor commented on [17] Aria TV 2 03 серия.ass
>  Dialogue: 0,0:22:17.44,0:22:23.73,Default,,0,0,0,,{\i1}Благодаря Ал-чану, сегодняшняя ночь метеоритного дождя прошла в тишине.
Нет, просто пометил чтоб вы с Димой случайно не исправили.
Можно в резолвд.

2023-06-08 17:52 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
>  Dialogue: 0,0:22:17.44,0:22:23.73,Default,,0,0,0,,{\i1}Благодаря Ал-чану, сегодняшняя ночь метеоритного дождя прошла в тишине.
Я про то, не нужно ли заменить на "Ал-чан"?

2023-06-08 18:08 UTC, KusanagiMajor commented on [17] Aria TV 2 03 серия.ass
>  Dialogue: 0,0:22:17.44,0:22:23.73,Default,,0,0,0,,{\i1}Благодаря Ал-чану, сегодняшняя ночь метеоритного дождя прошла в тишине.
Нене, не стоит

2023-06-09 04:15 UTC, KusanagiMajor commented
Ещё меня раздражает что субтитры почему-то цвета мочи.
Думаю после наших правок мы могли бы вернуть им благородный белый цвет.

Нужно просто заменить
> Default,Arial,60,&H000BFFFD

на
> Default,Arial,60,&H00FFFFFF

в каждой серии

2023-06-09 04:55 UTC, Paprikar commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:10:18.89,0:10:24.81,Default,,0,0,0,,Фактически, это кафе открылось более чем 580 лет назад в Венеции на Земле,
+

2023-06-09 04:55 UTC, Paprikar commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:14:17.64,0:14:24.88,Default,,0,0,0,,Это то, что сказал Наполеон о площади Сан Марко давным-давно на Земле.
+

2023-06-09 04:55 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:01:01.08,0:01:06.67,Default,,0,0,0,,На Земле погода всегда стабильна, но мне больше нравится Аква.
+

2023-06-09 04:55 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:12:17.01,0:12:19.02,Default,,0,0,0,,Вы двое, Смущающие высказывания запрещены!
+

2023-06-09 04:57 UTC, Paprikar commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:10:18.89,0:10:24.81,Default,,0,0,0,,Фактически, это кафе открылось более чем 580 лет назад в Венеции на Земле,
:heavy_check_mark:

2023-06-09 04:57 UTC, Paprikar commented on [16] Aria TV 2 02 серия.ass
> +Dialogue: 0,0:14:17.64,0:14:24.88,Default,,0,0,0,,Это то, что сказал Наполеон о площади Сан Марко давным-давно на Земле.
:white_check_mark:

2023-06-09 04:57 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:01:01.08,0:01:06.67,Default,,0,0,0,,На Земле погода всегда стабильна, но мне больше нравится Аква.
:heavy_check_mark:

2023-06-09 04:57 UTC, Paprikar commented on [17] Aria TV 2 03 серия.ass
> +Dialogue: 0,0:12:17.01,0:12:19.02,Default,,0,0,0,,Вы двое, Смущающие высказывания запрещены!
:heavy_check_mark:

2023-06-09 04:58 UTC, Paprikar commented on [23] Aria TV 2 09 серия.ass
> +Dialogue: 0,0:03:44.27,0:03:47.98,Default,,0,0,0,,и быстро стал очень популярным\Nв Венеции на Земле.
:heavy_check_mark:

2023-06-09 04:58 UTC, Paprikar commented on [32] Aria TV 2 18 серия.ass
> +Dialogue: 0,0:20:56.49,0:20:58.32,Default,,0,0,0,,Да, но Смущающие высказывания запрещены!
:heavy_check_mark:

2023-06-09 04:58 UTC, Paprikar commented on [34] Aria TV 2 20 серия.ass
> +Dialogue: 0,0:06:04.05,0:06:11.39,Default,,0,0,0,,Эти колонны всегда были олицетворением города, даже в Венеции на Земле.
:heavy_check_mark:

2023-06-09 04:58 UTC, Paprikar commented on [38] Aria TV 2 24 серия.ass
>  Dialogue: 0,0:07:21.86,0:07:24.19,Default,,0,0,0,,Атена-семпай - Сирена.
:heavy_check_mark:

2023-06-09 04:59 UTC, KusanagiMajor requested changes
Ещё меня раздражает что субтитры почему-то цвета мочи.
Думаю после наших правок мы могли бы вернуть им благородный белый цвет.

Нужно просто заменить
> Default,Arial,60,&H000BFFFD

на
> Default,Arial,60,&H00FFFFFF

в каждой серии

2023-06-09 06:00 UTC, Paprikar commented
> Ещё меня раздражает что субтитры почему-то цвета мочи. Думаю после наших правок мы могли бы вернуть им благородный белый цвет.
> 
> Нужно просто заменить
> 
> > Default,Arial,60,&H000BFFFD
> 
> на
> 
> > Default,Arial,60,&H00FFFFFF
> 
> в каждой серии

✔️

2023-06-09 09:52 UTC, KusanagiMajor commented on [14] Aria TV 2 Sp 1 серия.ass
> +Style: Default,Arial,60,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,2,30,30,30,204
почему гит видит разницу начиная с H00... а не с 0B... ?

2023-06-09 10:23 UTC, Paprikar commented on [14] Aria TV 2 Sp 1 серия.ass
> +Style: Default,Arial,60,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,2,30,30,30,204
Хз, видимо подсвечивает диффу по словам а не по символам (коды символов - правильные)

2023-06-09 10:33 UTC, KusanagiMajor commented on [19] Aria TV 2 05 серия.ass
Строка 53
Oinari-san - это не жареный тофу, это инари суши

Жареный тофу:
![image](https://github.com/Paprikar/aria-2-subs/assets/67715102/dfb4c7de-ff7d-4b93-8650-9941e89e9b02)

Инари суши:
![](https://susi-college.com/wp-content/uploads/2017/12/inari-sushi_4.jpg)

Технически это суши в мешочках из обжаренного тофу, китсуне любят тофу, и потому им нравятся инари, так как они завёрнуты в тофу. Проблема только в том, что в сабах всё перевели как жаренный тофу, хотя они там покупают инари.

В манге перевели так:
![](https://img33.imgslib.link//manga/aria/chapters/1-4/07.png)
![](https://img33.imgslib.link//manga/aria/chapters/1-4/33.png)

Итого надо заменить:

> Oinari-san (inarizushi), "inari" - жареный соевый творог: в японском фольклоре считается, что божественные лисы очень его любят.
на
> Oinari-san (inarizushi), "inari" - разновидность суши, завёрнутых в обжаренный тофу.

далее во всей серии заменить "жареный тофу" на "инари", кроме вот этой строчки:

> С давних пор, китсуне очень любят жареный тофу.

2023-06-09 10:34 UTC, KusanagiMajor commented on [19] Aria TV 2 05 серия.ass
Строка 87
грибной дождь -> слепой дождь

2023-06-09 11:39 UTC, hotoshi commented on [29] Aria TV 2 15 серия.ass
>  Dialogue: 0,0:04:45.81,0:04:47.56,Default,,0,0,0,,Ко-сич-ки!
Ко-сич-ки! -> Хво-сти-ки!

2023-06-09 12:34 UTC, Paprikar commented on [19] Aria TV 2 05 серия.ass
✅

2023-06-09 12:34 UTC, Paprikar commented on [19] Aria TV 2 05 серия.ass
✅

2023-06-09 12:34 UTC, Paprikar commented on [29] Aria TV 2 15 серия.ass
>  Dialogue: 0,0:04:45.81,0:04:47.56,Default,,0,0,0,,Ко-сич-ки!
✅

2023-06-09 12:36 UTC, Paprikar commented on [19] Aria TV 2 05 серия.ass
☑️

2023-06-09 12:38 UTC, KusanagiMajor approved these changes
С кайфом засмотрим теперь

2023-06-09 12:43 UTC, hotoshi commented on [36] Aria TV 2 22 серия.ass
220 Кэрри со свиными котлетами -> Карри со свиными котлетами.

2023-06-09 13:15 UTC, hotoshi commented on [19] Aria TV 2 05 серия.ass
>  Dialogue: 0,0:10:49.46,0:10:54.30,Default,,0,0,0,,С давних пор, китсуне очень любят жареный тофу.
С давних пор, китсуне очень любят жареный тофу -> С давних пор, китсуне очень любят инари?

2023-06-09 13:25 UTC, Paprikar commented on [36] Aria TV 2 22 серия.ass
✅

2023-06-09 13:29 UTC, hotoshi approved these changes

2023-06-09 13:30 UTC, KusanagiMajor approved these changes

2023-06-09 13:30 UTC, merged